version: '2'

networks:
  peacetrue-microservice:
    external:
      name: peacetrue-microservice

services:
  rabbitmq:
    image: jenkinsci/blueocean
    container_name: jenkins
    hostname: jenkins
    expose:
      - 8080
      - 50000
    ports:
      - 8400:8080
      - 50000:50000
    volumes:
      - ./volumes/jenkins-data/:/var/jenkins_home
      - ./volumes/var/run/docker.sock:/var/run/docker.sock
    networks:
      - peacetrue-microservice

# 启动
# docker-compose up -d

# 访问页面
# http://peacetrue.cn:8400
# http://localhost:8400
