version: '2'

networks:
  peacetrue-microservice:
    external:
      name: peacetrue-microservice

services:
#  jenkins-docker:
#    image: docker:dind
#    container_name: jenkins-docker
#    hostname: jenkins-docker
#    privileged: true
#    expose:
#      - 2376
#    ports:
#      - 2376:2376
##    environment:
##      DOCKER_TLS_CERTDIR: /certs
#    volumes:
##      - ./volumes/jenkins-docker-certs:/certs/client
#      - ./volumes/jenkins-data:/var/jenkins_home
#    networks:
#      - peacetrue-microservice
#  jenkins-blueocean:
#    image: jenkinsci/blueocean
#    container_name: jenkins-blueocean
#    hostname: jenkins-blueocean
#    expose:
#      - 8080
#      - 50000
#    ports:
#      - 8400:8080
#      - 50000:50000
#    environment:
#      DOCKER_HOST: tcp://docker:2376
##      DOCKER_CERT_PATH: /certs/client
##      DOCKER_TLS_VERIFY: 1
#    volumes:
#      - ./volumes/jenkins-data:/var/jenkins_home
##      - ./volumes/jenkins-docker-certs:/certs/client:ro
#    networks:
#      - peacetrue-microservice
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8400:8080
      - 50000:50000
    #environment:
    #  DOCKER_HOST: tcp://docker:2376
    #      DOCKER_CERT_PATH: /certs/client
    #      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./volumes/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    #- ./volumes/jenkins-docker-certs:/certs/client:ro
    networks:
      - peacetrue-microservice

# 启动
# docker-compose up -d

#赋予权限
# sudo chown -R 1000:1000 ./volumes
# chmod 777 /var/run/docker.sock
# docker exec -it jenkins bash

# 访问页面
# http://jenkins.peacetrue.cn:8400
# http://localhost:8400
